### ISSUE TITLE
Comparison raises notimplementederror in Chainer

### ISSUE THREAD

**Issue by Tamme** [shiba24/deep-learning-for-human-part-discovery-in-images#1]
When using all the suggested parameters, but CPU, instead of GPU and the initial model in pkl format provided by you, I get this error:

loading VGG model...
('training datasets: ', 9788, 'test datasets: ', 516)
Epoch 1 : training...
0it [00:00, ?it/s]Create Iterator settings

Traceback (most recent call last):
  File "train.py", line 102, in <module>
    model, optimizer, train_mean_loss, train_ac = train(model, optimizer, MiniBatchLoader, train_mean_loss, train_ac)
  File "train.py", line 31, in train
    optimizer.update(model, x, t)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 392, in update
    loss = lossfun(_args, *_kwds)
  File "/home/tamme/Desktop/humanparts/model.py", line 86, in **call**
    self.accuracy = self.calculate_accuracy(h, t)
  File "/home/tamme/Desktop/humanparts/model.py", line 168, in calculate_accuracy
    mask = truths != -1
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 463, in **ne**
    raise NotImplementedError()
NotImplementedError

Is it a bug or have I done something incorrectly? I don't seem to find a related problem in google either.

**Comment by shiba24** [comment]
Hi @Tamme , thank you for the report.
Could you tell me the version of chainer are you using?

**Comment by Tamme** [comment]
Im using Chainer 1.16.0 and Ubuntu 14.04.

**Comment by shiba24** [comment]
@Tamme I found the bug for the CPU mode and I think it is fixed now! Would you try it and tell me if it still raises some error! thanks.
