### ISSUE TITLE
TypeError: __init__() got unexpected keyword argument(s) 'wscale' heeeeellllllppppppppppppppp

### ISSUE THREAD

**Issue by leisther** [shiba24/deep-learning-for-human-part-discovery-in-images#15]
loading VGG model...
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    model = HumanPartsNet(n_class=15)
  File "/home/leisther/Downloads/deep-learning-for-human-part-discovery-in-images-master/model.py", line 53, in __init__
    upsample_pool1=L.Convolution2D(64, self.n_class, ksize=1, stride=1, pad=0, wscale=0.01),
  File "/home/leisther/anaconda2/envs/venv/lib/python2.7/site-packages/chainer/links/connection/convolution_2d.py", line 120, in __init__
    deterministic="deterministic argument is not supported anymore. "
  File "/home/leisther/anaconda2/envs/venv/lib/python2.7/site-packages/chainer/utils/argument.py", line 19, in parse_kwargs
    raise TypeError(message)
TypeError: __init__() got unexpected keyword argument(s) 'wscale'

**Comment by SajjadAemmi** [comment]
i have this error too :(
