### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by cricket1** [shiba24/deep-learning-for-human-part-discovery-in-images#3]
- I am using a p2 instance on aws .I ran python train.py -g 0 -b 5 -e 3000 -l on -s on

And I am getting 

> loading VGG model...
('training datasets: ', 9788, 'test datasets: ', 516)
Epoch 1 : training...
0it [00:00, ?it/s]Create Iterator settings
1it [00:04,  4.19s/it]Traceback (most recent call last):
  File "train.py", line 102, in <module>
    model, optimizer, train_mean_loss, train_ac = train(model, optimizer, MiniBatchLoader, train_mean_loss, train_ac)
  File "train.py", line 27, in train
    for X, y in tqdm(MiniBatchLoader):
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 816, in __iter__
    for obj in iterable:
  File "/home/ubuntu/deep-learning-for-human-part-discovery-in-images/data.py", line 83, in next
    minibatch_X, minibatch_y = self.process_batch(minibatch_X, minibatch_y)
  File "/home/ubuntu/deep-learning-for-human-part-discovery-in-images/data.py", line 145, in process_batch
    reshaped_X = np.transpose(self.standardize(processed_X), (0, 3, 1, 2))        # n_batch, n_channel, h, w
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 556, in transpose
    return transpose(axes)
ValueError: axes don't match array

> 

- Update - I am not able to reproduce the issue .Everything seems to be working fine now

**Comment by shiba24** [comment]
@cricket1  Thank you for the report! If you find some bugs please tell me :)
